language: c
sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install cpanminus nsis
  - sudo cpanm --notest Config::AutoConf::INI ExtUtils::CBuilder File::chdir File::Basename File::Find File::Path File::Copy::Recursive IPC::Run
# Dependencies
  - sh ./install-c-genericLogger.sh
  - sh ./install-c-genericStack.sh
  - sh ./install-c-genericHash.sh
  - sh ./install-c-genericSparseArray.sh
script:
# We want to try perl standalone first
  - perl CMakeObjects.PL
  - rm -rf output
# ALL_IN_ONE
  - cmake . -DALL_IN_ONE=ON
  - make check
  - make pack
  - cpack -G NSIS
  - make install DESTDIR=/tmp
  - rm -rf output CMakeCache.txt CMakeFiles
# Not ALL_IN_ONE
  - cmake .
  - make check
  - make pack
  - cpack -G NSIS
  - sudo make install
