#ifndef MARPAESLIF_YAML_INTERNAL_STRUCTURES_H
#define MARPAESLIF_YAML_INTERNAL_STRUCTURES_H

#include "marpaESLIF_YAML/internal/model/information.h"

#endif /* MARPAESLIF_YAML_INTERNAL_STRUCTURES_H */
